jobs:
  - name: microservice-manifest
    type: manifest
    steps:
     - IN: microservice-img
     - TASK: managed

  - name: microservice-deploy
    type: deploy
    steps:
      - IN: microservice-manifest
      - IN: microservice-img-options
      - IN: ecs-test-cluster
      - IN: microservice-mgmt-elb
        applyTo:
          - manifest: microservice-manifest
            image: microservice-img
            port: 80
      - IN: microservice-mgmt-elb
        applyTo:
          - manifest: microservice-manifest
            image: microservice-img
            port: 8888
      - TASK: managed
        deployMethod: blueGreen
